### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by AdiEcho** [ShangguanQuail/pandatv#2]
`sh: 1: nodemon: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pandatv@1.0.0 start: `nodemon -x node index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pandatv@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-19T05_35_20_222Z-debug.log
`
大佬求解答

**Comment by channg** [comment]
npm install -g nodemon

> 没什么用，抢不到的。

**Comment by AdiEcho** [comment]
@channg 好吧，看来又要手动抢了。请问你也是自己抢的嘛？

**Comment by ShangguanQuail** [comment]
@AdiEcho 抱歉，抢竹子是一个多任务并行的场景，和node的单线程的模型不太符合，所以这个项目没继续往下写了。有兴趣的话可以参考里面对headless的操作，用其他语言重写。

**Comment by lv100** [comment]
开始看到以为可以领宝箱的竹子呢
